### ISSUE TITLE
Need to start my jupyter service on port 80 not on 8888

### ISSUE THREAD

**Issue by iankittomar** [UNINETT/helm-charts#7]
**In values.yaml i wrote :**
ports:
  http: 80
probe:
  initialdelayseconds: 15
  timeoutseconds: 5    
replicas: 1

**In deployment.yaml i wrote :**
containers:
      - name: {{.Values.container.name}}
        image: {{.Values.global.docker.registry}}/{{.Values.container.image}} 
        imagePullPolicy: Always     
        ports:
        - containerPort: {{.Values.ports.http}}
          name: http
        readinessProbe:
          tcpSocket:
            port: {{.Values.ports.http | int}}
          initialDelaySeconds: {{.Values.probe.initialdelayseconds}}
          timeoutSeconds: {{.Values.probe.timeoutseconds}}
        livenessProbe:
          tcpSocket:
            port: {{.Values.ports.http | int}}
          initialDelaySeconds: {{.Values.probe.initialdelayseconds}}
          timeoutSeconds: {{.Values.probe.timeoutseconds}} 

**In service.yaml is wrote :** 
 spec:
  ports:
 - port: {{.Values.ports.http}}
    name: http
  selector:
    app: jupyter-{{.Release.Name}}
  type: LoadBalancer

**i need to start my jupyter on port 80, I am able to start my services its shows (80:3064) but not able to access in browser.

I have tried every method. Please help me.**

**Comment by paalka** [comment]
This issue isn't really related to this repo, especially since you are not using the jupyter chart hosted in this repo, but I can try to help regardless.

1. Are you sure the deployment actually works? If you run `kubectl get pod`, is the jupyter pod running properly? If it is running properly, have you for instance tried to [port-forward](https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/)
the port which the jupyter pod uses to a port on your local machine?

2. In kubernetes, a [ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) is usually used to expose a service to the outside world, have you tried using a ingress?
